# The PROJECT_ID is a cloud build env variable
steps:
  - id: 'Terraform init'
    name: 'hashicorp/terraform:0.12.20'
    dir: 'terraform'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform init -input=false
        terraform workspace select pdf-pipeline || terraform workspace new pdf-pipeline
        terraform apply -input=false -auto-approve
    waitFor: ['-']